use once_cell::sync::Lazy;

#[derive(Clone, Copy)]
pub struct Grace {
    pub main_area: &'static str,
    pub name: &'static str,
    pub grace_entity_id: i64,
    pub flag_id: i32,
    pub dlc: bool,
}

pub fn graces_array(dlc_available: bool) -> &'static [Grace] {
    if dlc_available {
        &GRACES
    } else {
        &GRACES_NO_DLC
    }
}

static GRACES_NO_DLC: Lazy<Vec<Grace>> = Lazy::new(|| {
    GRACES.iter().filter(|grace| !grace.dlc).cloned().collect()
});

static GRACES: [Grace; 419] = [
    Grace {
        main_area: "Roundtable Hold",
        name: "Table of Lost Grace",
        grace_entity_id: 11101950,
        flag_id: 71190,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "The First Step",
        grace_entity_id: 1042361951,
        flag_id: 76101,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Church of Elleh",
        grace_entity_id: 1042361950,
        flag_id: 76100,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Gatefront",
        grace_entity_id: 1042371950,
        flag_id: 76111,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Waypoint Ruins Cellar",
        grace_entity_id: 1044361950,
        flag_id: 76120,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Artist's Shack",
        grace_entity_id: 1044381950,
        flag_id: 76103,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Third Church of Marika",
        grace_entity_id: 1046381950,
        flag_id: 76104,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Fort Haight West",
        grace_entity_id: 1045361950,
        flag_id: 76105,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Agheel Lake South",
        grace_entity_id: 1044351950,
        flag_id: 76106,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Agheel Lake North",
        grace_entity_id: 1043371950,
        flag_id: 76108,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Church of Dragon Communion",
        grace_entity_id: 1041351950,
        flag_id: 76110,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Seaside Ruins",
        grace_entity_id: 1043351950,
        flag_id: 76113,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Mistwood Outskirts",
        grace_entity_id: 1044371950,
        flag_id: 76114,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Murkwater Coast",
        grace_entity_id: 1043381950,
        flag_id: 76116,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Summonwater Village Outskirts",
        grace_entity_id: 1044391950,
        flag_id: 76119,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Stormfoot Catacombs",
        grace_entity_id: 30021950,
        flag_id: 73002,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Murkwater Catacombs",
        grace_entity_id: 30041950,
        flag_id: 73004,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Groveside Cave",
        grace_entity_id: 31031950,
        flag_id: 73103,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Coastal Cave",
        grace_entity_id: 31151950,
        flag_id: 73115,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Murkwater Cave",
        grace_entity_id: 31001950,
        flag_id: 73100,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Highroad Cave",
        grace_entity_id: 31171950,
        flag_id: 73117,
        dlc: false,
    },
    Grace {
        main_area: "Limgrave",
        name: "Limgrave Tunnels",
        grace_entity_id: 32011950,
        flag_id: 73201,
        dlc: false,
    },
    Grace {
        main_area: "Stranded Graveyard",
        name: "Cave of Knowledge",
        grace_entity_id: 18001950,
        flag_id: 71800,
        dlc: false,
    },
    Grace {
        main_area: "Stranded Graveyard",
        name: "Stranded Graveyard",
        grace_entity_id: 18001951,
        flag_id: 71801,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Stormhill Shack",
        grace_entity_id: 1041381950,
        flag_id: 76102,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Castleward Tunnel",
        grace_entity_id: 10001952,
        flag_id: 71002,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Margit, the Fell Omen",
        grace_entity_id: 10001951,
        flag_id: 71001,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Warmaster's Shack",
        grace_entity_id: 1042381950,
        flag_id: 76118,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Saintsbridge",
        grace_entity_id: 1043391950,
        flag_id: 76117,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Deathtouched Catacombs",
        grace_entity_id: 30111950,
        flag_id: 73011,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Limgrave Tower Bridge",
        grace_entity_id: 34101950,
        flag_id: 73410,
        dlc: false,
    },
    Grace {
        main_area: "Stormhill",
        name: "Divine Tower of Limgrave",
        grace_entity_id: 34101952,
        flag_id: 73412,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Church of Pilgrimage",
        grace_entity_id: 1043341950,
        flag_id: 76150,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Castle Morne Rampart",
        grace_entity_id: 1044331950,
        flag_id: 76151,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Tombsward",
        grace_entity_id: 1042331950,
        flag_id: 76152,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "South of the Lookout Tower",
        grace_entity_id: 1044331951,
        flag_id: 76153,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Ailing Village Outskirts",
        grace_entity_id: 1044331952,
        flag_id: 76154,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Beside the Crater-Pocked Glade",
        grace_entity_id: 1045331950,
        flag_id: 76155,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Isolated Merchant's Shack",
        grace_entity_id: 1041321950,
        flag_id: 76156,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Fourth Church of Marika",
        grace_entity_id: 1041331950,
        flag_id: 76162,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Bridge of Sacrifice",
        grace_entity_id: 1044341950,
        flag_id: 76157,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Castle Morne Lift",
        grace_entity_id: 1043311950,
        flag_id: 76158,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Behind the Castle",
        grace_entity_id: 1043311951,
        flag_id: 76159,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Beside the Rampart Gaol",
        grace_entity_id: 1043311952,
        flag_id: 76160,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Morne Moangrave",
        grace_entity_id: 1043301950,
        flag_id: 76161,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Impaler's Catacombs",
        grace_entity_id: 30011950,
        flag_id: 73001,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Tombsward Catacombs",
        grace_entity_id: 30001950,
        flag_id: 73000,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Earthbore Cave",
        grace_entity_id: 31011950,
        flag_id: 73101,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Tombsward Cave",
        grace_entity_id: 31021950,
        flag_id: 73102,
        dlc: false,
    },
    Grace {
        main_area: "Weeping Peninsula",
        name: "Morne Tunnel",
        grace_entity_id: 32001950,
        flag_id: 73200,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Stormveil Main Gate",
        grace_entity_id: 10001958,
        flag_id: 71008,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Gateside Chamber",
        grace_entity_id: 10001953,
        flag_id: 71003,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Stormveil Cliffside",
        grace_entity_id: 10001954,
        flag_id: 71004,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Rampart Tower",
        grace_entity_id: 10001955,
        flag_id: 71005,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Liftside Chamber",
        grace_entity_id: 10001956,
        flag_id: 71006,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Secluded Cell",
        grace_entity_id: 10001957,
        flag_id: 71007,
        dlc: false,
    },
    Grace {
        main_area: "Stormveil Castle",
        name: "Godrick the Grafted",
        grace_entity_id: 10001950,
        flag_id: 71000,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Lake-Facing Cliffs",
        grace_entity_id: 1039401950,
        flag_id: 76200,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Liurnia Lake Shore",
        grace_entity_id: 1038401950,
        flag_id: 76201,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Laskyar Ruins",
        grace_entity_id: 1038411950,
        flag_id: 76202,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Scenic Isle",
        grace_entity_id: 1037421950,
        flag_id: 76203,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Academy Gate Town",
        grace_entity_id: 1037441950,
        flag_id: 76204,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "South Raya Lucaria Gate",
        grace_entity_id: 1035451950,
        flag_id: 76205,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Main Academy Gate",
        grace_entity_id: 1035461950,
        flag_id: 76206,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Liurnia Highway South",
        grace_entity_id: 1039411950,
        flag_id: 76244,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Liurnia Highway North",
        grace_entity_id: 1039421950,
        flag_id: 76221,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Gate Town Bridge",
        grace_entity_id: 1038431950,
        flag_id: 76222,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Artist's Shack",
        grace_entity_id: 1038451950,
        flag_id: 76217,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Eastern Liurnia Lake Shore",
        grace_entity_id: 1038451951,
        flag_id: 76223,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Ranni's Chamber",
        grace_entity_id: 1034501951,
        flag_id: 76247,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Jarburg",
        grace_entity_id: 1039441950,
        flag_id: 76245,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Eastern Tableland",
        grace_entity_id: 1038461950,
        flag_id: 76234,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Church of Vows",
        grace_entity_id: 1037461950,
        flag_id: 76224,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Ruined Labyrinth",
        grace_entity_id: 1038471950,
        flag_id: 76225,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Mausoleum Compound",
        grace_entity_id: 1037481950,
        flag_id: 76226,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Slumbering Wolf's Shack",
        grace_entity_id: 1036411950,
        flag_id: 76215,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Boilprawn Shack",
        grace_entity_id: 1036431950,
        flag_id: 76216,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Fallen Ruins of the Lake",
        grace_entity_id: 1036431951,
        flag_id: 76236,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Folly on the Lake",
        grace_entity_id: 1035431950,
        flag_id: 76219,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Village of the Albinaurics",
        grace_entity_id: 1034421950,
        flag_id: 76220,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Converted Tower",
        grace_entity_id: 1034431950,
        flag_id: 76237,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Revenger's Shack",
        grace_entity_id: 1033441950,
        flag_id: 76218,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Temple Quarter",
        grace_entity_id: 1034441950,
        flag_id: 76241,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Crystalline Woods",
        grace_entity_id: 1034461950,
        flag_id: 76243,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Foot of the Four Belfries",
        grace_entity_id: 1033461950,
        flag_id: 76210,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "The Four Belfries",
        grace_entity_id: 1033471950,
        flag_id: 76227,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Sorcerer's Isle",
        grace_entity_id: 1034471951,
        flag_id: 76211,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "East Gate Bridge Trestle",
        grace_entity_id: 1035471950,
        flag_id: 76242,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Gate Town North",
        grace_entity_id: 1036451950,
        flag_id: 76233,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Northern Liurnia Lake Shore",
        grace_entity_id: 1034481950,
        flag_id: 76212,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Road to the Manor",
        grace_entity_id: 1034491950,
        flag_id: 76213,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Main Caria Manor Gate",
        grace_entity_id: 1035501953,
        flag_id: 76214,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Manor Upper Level",
        grace_entity_id: 1035501950,
        flag_id: 76230,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Manor Lower Level",
        grace_entity_id: 1035501951,
        flag_id: 76231,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Royal Moongazing Grounds",
        grace_entity_id: 1035501952,
        flag_id: 76232,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Ranni's Rise",
        grace_entity_id: 1034501950,
        flag_id: 76228,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Behind Caria Manor",
        grace_entity_id: 1036501950,
        flag_id: 76238,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "The Ravine",
        grace_entity_id: 1036491951,
        flag_id: 76235,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Ravine-Veiled Village",
        grace_entity_id: 1038501951,
        flag_id: 76229,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Cliffbottom Catacombs",
        grace_entity_id: 30061950,
        flag_id: 73006,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Road's End Catacombs",
        grace_entity_id: 30031950,
        flag_id: 73003,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Black Knife Catacombs",
        grace_entity_id: 30051950,
        flag_id: 73005,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Stillwater Cave",
        grace_entity_id: 31041950,
        flag_id: 73104,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Lakeside Crystal Cave",
        grace_entity_id: 31051950,
        flag_id: 73105,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Academy Crystal Cave",
        grace_entity_id: 31061950,
        flag_id: 73106,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Raya Lucaria Crystal Tunnel",
        grace_entity_id: 32021950,
        flag_id: 73202,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Study Hall Entrance",
        grace_entity_id: 34111950,
        flag_id: 73420,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Liurnia Tower Bridge",
        grace_entity_id: 34111951,
        flag_id: 73421,
        dlc: false,
    },
    Grace {
        main_area: "Liurnia of the Lakes",
        name: "Divine Tower of Liurnia",
        grace_entity_id: 34111952,
        flag_id: 73422,
        dlc: false,
    },
    Grace {
        main_area: "Bellum Highway",
        name: "East Raya Lucaria Gate",
        grace_entity_id: 1036481950,
        flag_id: 76207,
        dlc: false,
    },
    Grace {
        main_area: "Bellum Highway",
        name: "Bellum Church",
        grace_entity_id: 1036491950,
        flag_id: 76208,
        dlc: false,
    },
    Grace {
        main_area: "Bellum Highway",
        name: "Grand Lift of Dectus",
        grace_entity_id: 1038501950,
        flag_id: 76209,
        dlc: false,
    },
    Grace {
        main_area: "Bellum Highway",
        name: "Frenzied Flame Village Outskirts",
        grace_entity_id: 1038481950,
        flag_id: 76239,
        dlc: false,
    },
    Grace {
        main_area: "Bellum Highway",
        name: "Church of Inhibition",
        grace_entity_id: 1037491950,
        flag_id: 76240,
        dlc: false,
    },
    Grace {
        main_area: "Ruin-Strewn Precipice",
        name: "Ruin-Strewn Precipice",
        grace_entity_id: 39201951,
        flag_id: 73901,
        dlc: false,
    },
    Grace {
        main_area: "Ruin-Strewn Precipice",
        name: "Ruin-Strewn Precipice Overlook",
        grace_entity_id: 39201952,
        flag_id: 73902,
        dlc: false,
    },
    Grace {
        main_area: "Ruin-Strewn Precipice",
        name: "Magma Wyrm Makar",
        grace_entity_id: 39201950,
        flag_id: 73900,
        dlc: false,
    },
    Grace {
        main_area: "Moonlight Altar",
        name: "Moonlight Altar",
        grace_entity_id: 1034411950,
        flag_id: 76250,
        dlc: false,
    },
    Grace {
        main_area: "Moonlight Altar",
        name: "Cathedral of Manus Celes",
        grace_entity_id: 1035421950,
        flag_id: 76251,
        dlc: false,
    },
    Grace {
        main_area: "Moonlight Altar",
        name: "Altar South",
        grace_entity_id: 1033401950,
        flag_id: 76252,
        dlc: false,
    },
    Grace {
        main_area: "Academy of Raya Lucaria",
        name: "Schoolhouse Classroom",
        grace_entity_id: 14001953,
        flag_id: 71403,
        dlc: false,
    },
    Grace {
        main_area: "Academy of Raya Lucaria",
        name: "Church of the Cuckoo",
        grace_entity_id: 14001952,
        flag_id: 71402,
        dlc: false,
    },
    Grace {
        main_area: "Academy of Raya Lucaria",
        name: "Debate Parlor",
        grace_entity_id: 14001951,
        flag_id: 71401,
        dlc: false,
    },
    Grace {
        main_area: "Academy of Raya Lucaria",
        name: "Raya Lucaria Grand Library",
        grace_entity_id: 14001950,
        flag_id: 71400,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Abandoned Coffin",
        grace_entity_id: 1037511950,
        flag_id: 76300,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Erdtree-Gazing Hill",
        grace_entity_id: 1038511950,
        flag_id: 76302,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Altus Plateau",
        grace_entity_id: 1038501952,
        flag_id: 76301,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Altus Highway Junction",
        grace_entity_id: 1039511950,
        flag_id: 76303,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Forest-Spanning Greatbridge",
        grace_entity_id: 1040521950,
        flag_id: 76304,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Bower of Bounty",
        grace_entity_id: 1040531950,
        flag_id: 76306,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Windmill Village",
        grace_entity_id: 1041541950,
        flag_id: 76308,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Windmill Heights",
        grace_entity_id: 1042551950,
        flag_id: 76313,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Road of Iniquity Side Path",
        grace_entity_id: 1040541950,
        flag_id: 76307,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Rampartside Path",
        grace_entity_id: 1041521951,
        flag_id: 76305,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Shaded Castle Ramparts",
        grace_entity_id: 1039541950,
        flag_id: 76320,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Shaded castle Inner Gate",
        grace_entity_id: 1039541951,
        flag_id: 76321,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Castellan's Hall",
        grace_entity_id: 1039541952,
        flag_id: 76322,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Unsightly Catacombs",
        grace_entity_id: 30121950,
        flag_id: 73012,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Sainted Hero's Grave",
        grace_entity_id: 30081950,
        flag_id: 73008,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Sage's Cave",
        grace_entity_id: 31191950,
        flag_id: 73119,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Perfumer's Grotto",
        grace_entity_id: 31181950,
        flag_id: 73118,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Old Altus Tunnel",
        grace_entity_id: 32041950,
        flag_id: 73204,
        dlc: false,
    },
    Grace {
        main_area: "Altus Plateau",
        name: "Altus Tunnel",
        grace_entity_id: 32051950,
        flag_id: 73205,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Bridge of Iniquity",
        grace_entity_id: 1039531950,
        flag_id: 76350,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "First Mt. Gelmir Campsite",
        grace_entity_id: 1038541950,
        flag_id: 76351,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Ninth Mt. Gelmir Campsite",
        grace_entity_id: 1036541951,
        flag_id: 76352,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Road of Iniquity",
        grace_entity_id: 1036541952,
        flag_id: 76353,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Seethewater River",
        grace_entity_id: 1037521951,
        flag_id: 76354,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Seethewater Terminus",
        grace_entity_id: 1035531950,
        flag_id: 76355,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Craftman's Shack",
        grace_entity_id: 1036521950,
        flag_id: 76356,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Primeval Sorcerer Azur",
        grace_entity_id: 1037531950,
        flag_id: 76357,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Wyndham Catacombs",
        grace_entity_id: 30071950,
        flag_id: 73007,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Gelmir Hero's Grave",
        grace_entity_id: 30091950,
        flag_id: 73009,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Seethewater Cave",
        grace_entity_id: 31071950,
        flag_id: 73107,
        dlc: false,
    },
    Grace {
        main_area: "Mt. Gelmir",
        name: "Volcano Cave",
        grace_entity_id: 31091950,
        flag_id: 73109,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Outer Wall Phantom Tree",
        grace_entity_id: 1042511950,
        flag_id: 76309,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Minor Erdtree Church",
        grace_entity_id: 1043501950,
        flag_id: 76310,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Outer Wall Battleground",
        grace_entity_id: 1043531951,
        flag_id: 76312,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Hermit Merchant's Shack",
        grace_entity_id: 1043531950,
        flag_id: 76311,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Capital Rampart",
        grace_entity_id: 1045521950,
        flag_id: 76314,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Auriza Side Tomb",
        grace_entity_id: 30131950,
        flag_id: 73013,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Auriza Hero's Grave",
        grace_entity_id: 30101950,
        flag_id: 73010,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Sealed Tunnel",
        grace_entity_id: 34121951,
        flag_id: 73431,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Divine Tower of West Altus",
        grace_entity_id: 34121950,
        flag_id: 73430,
        dlc: false,
    },
    Grace {
        main_area: "Capital Outskirts",
        name: "Divine Tower of West Altus: Gate",
        grace_entity_id: 34121952,
        flag_id: 73432,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Volcano Manor",
        grace_entity_id: 16001952,
        flag_id: 71602,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Prison Town Church",
        grace_entity_id: 16001953,
        flag_id: 71603,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Temple of Eiglay",
        grace_entity_id: 16001951,
        flag_id: 71601,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Guest Hall",
        grace_entity_id: 16001954,
        flag_id: 71604,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Audience Pathway",
        grace_entity_id: 16001960,
        flag_id: 71605,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Abductor Virgin",
        grace_entity_id: 16001962,
        flag_id: 71606,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Subterranean Inquisition Chamber",
        grace_entity_id: 16001964,
        flag_id: 71607,
        dlc: false,
    },
    Grace {
        main_area: "Volcano Manor",
        name: "Rykard, Lord of Blasphemy",
        grace_entity_id: 16001950,
        flag_id: 71600,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Erdtree Sanctuary",
        grace_entity_id: 11001951,
        flag_id: 71101,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "East Capital Rampart",
        grace_entity_id: 11001952,
        flag_id: 71102,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Lower Capital Church",
        grace_entity_id: 11001953,
        flag_id: 71103,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Avenue Balcony",
        grace_entity_id: 11001954,
        flag_id: 71104,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "West Capital Rampart",
        grace_entity_id: 11001955,
        flag_id: 71105,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Queen's Bedchamber",
        grace_entity_id: 11001957,
        flag_id: 71107,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Fortified Manor, First Floor",
        grace_entity_id: 11001958,
        flag_id: 71108,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Divine Bridge",
        grace_entity_id: 11001959,
        flag_id: 71109,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Royal Capital",
        name: "Elden Throne",
        grace_entity_id: 11001950,
        flag_id: 71100,
        dlc: false,
    },
    Grace {
        main_area: "Subterranean Shunning-Grounds",
        name: "Underground Roadside",
        grace_entity_id: 35001951,
        flag_id: 73501,
        dlc: false,
    },
    Grace {
        main_area: "Subterranean Shunning-Grounds",
        name: "Forsaken Depths",
        grace_entity_id: 35001952,
        flag_id: 73502,
        dlc: false,
    },
    Grace {
        main_area: "Subterranean Shunning-Grounds",
        name: "Leyndell Catacombs",
        grace_entity_id: 35001953,
        flag_id: 73503,
        dlc: false,
    },
    Grace {
        main_area: "Subterranean Shunning-Grounds",
        name: "Frenzied Flame Proscription",
        grace_entity_id: 35001954,
        flag_id: 73504,
        dlc: false,
    },
    Grace {
        main_area: "Subterranean Shunning-Grounds",
        name: "Cathedral of the Forsaken",
        grace_entity_id: 35001950,
        flag_id: 73500,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "East Capital Rampart",
        grace_entity_id: 11051952,
        flag_id: 71122,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "Leyndell, Capital of Ash",
        grace_entity_id: 11051953,
        flag_id: 71123,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "Erdtree Sanctuary",
        grace_entity_id: 11051951,
        flag_id: 71121,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "Queen's Bedchamber",
        grace_entity_id: 11051954,
        flag_id: 71124,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "Divine Bridge",
        grace_entity_id: 11051955,
        flag_id: 71125,
        dlc: false,
    },
    Grace {
        main_area: "Leyndell, Ashen Capital",
        name: "Elden Throne",
        grace_entity_id: 11051950,
        flag_id: 71120,
        dlc: false,
    },
    Grace {
        main_area: "Stone Platform",
        name: "Fractured Marika",
        grace_entity_id: 19001950,
        flag_id: 71900,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Smoldering Church",
        grace_entity_id: 1046401950,
        flag_id: 76400,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Rotview Balcony",
        grace_entity_id: 1046401951,
        flag_id: 76401,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Caelem Ruins",
        grace_entity_id: 1047401950,
        flag_id: 76403,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Fort Gael North",
        grace_entity_id: 1047391950,
        flag_id: 76402,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Smoldering Wall",
        grace_entity_id: 1048391950,
        flag_id: 76409,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Caelid Highway South",
        grace_entity_id: 1048371950,
        flag_id: 76405,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Cathedral of Dragon Communion",
        grace_entity_id: 1048361950,
        flag_id: 76404,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Southern Aeonia Swamp Bank",
        grace_entity_id: 1049371950,
        flag_id: 76411,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Sellia Backstreets",
        grace_entity_id: 1049391950,
        flag_id: 76414,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Sellia Under-Stair",
        grace_entity_id: 1049391952,
        flag_id: 76416,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Chair-Crypt of Sellia",
        grace_entity_id: 1049391951,
        flag_id: 76415,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Church of the Plague",
        grace_entity_id: 1050381950,
        flag_id: 76418,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Deep Siofra Well",
        grace_entity_id: 1048401950,
        flag_id: 76410,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Impassable Greatbridge",
        grace_entity_id: 1050361950,
        flag_id: 76417,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Chamber Outside the Plaza",
        grace_entity_id: 1051361951,
        flag_id: 76420,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Redmane Castle Plaza",
        grace_entity_id: 1051361950,
        flag_id: 76419,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Starscourge Radahn",
        grace_entity_id: 1052381950,
        flag_id: 76422,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Minor Erdtree Catacombs",
        grace_entity_id: 30141950,
        flag_id: 73014,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Caelid Catacombs",
        grace_entity_id: 30151950,
        flag_id: 73015,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "War-Dead Catacombs",
        grace_entity_id: 30161950,
        flag_id: 73016,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Abandoned Cave",
        grace_entity_id: 31201950,
        flag_id: 73120,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Gaol Cave",
        grace_entity_id: 31211950,
        flag_id: 73121,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Gael Tunnel",
        grace_entity_id: 32071950,
        flag_id: 73207,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Rear Gael Tunnel Entrance",
        grace_entity_id: 32071951,
        flag_id: 73257,
        dlc: false,
    },
    Grace {
        main_area: "Caelid",
        name: "Sellia Crystal Tunnel",
        grace_entity_id: 32081950,
        flag_id: 73208,
        dlc: false,
    },
    Grace {
        main_area: "Swamp of Aeonia",
        name: "Aeonia Swamp Shore",
        grace_entity_id: 1048381950,
        flag_id: 76406,
        dlc: false,
    },
    Grace {
        main_area: "Swamp of Aeonia",
        name: "Astray from Caelid Highway North",
        grace_entity_id: 1048381951,
        flag_id: 76407,
        dlc: false,
    },
    Grace {
        main_area: "Swamp of Aeonia",
        name: "Heart of Aeonia",
        grace_entity_id: 1049381950,
        flag_id: 76412,
        dlc: false,
    },
    Grace {
        main_area: "Swamp of Aeonia",
        name: "Inner Aeonia",
        grace_entity_id: 1049381951,
        flag_id: 76413,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Dragonbarrow West",
        grace_entity_id: 1048401951,
        flag_id: 76450,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Isolated Merchant's Shack",
        grace_entity_id: 1048411950,
        flag_id: 76451,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Fort Faroth",
        grace_entity_id: 1051391950,
        flag_id: 76453,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Dragonbarrow Fork",
        grace_entity_id: 1050401950,
        flag_id: 76452,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Lenne's Rise",
        grace_entity_id: 1052411950,
        flag_id: 76455,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Farum Greatbridge",
        grace_entity_id: 1052421950,
        flag_id: 76456,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Bestial Sanctum",
        grace_entity_id: 1051431950,
        flag_id: 76454,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Sellia Hideaway",
        grace_entity_id: 31111950,
        flag_id: 73111,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Dragonbarrow Cave",
        grace_entity_id: 31101950,
        flag_id: 73110,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Divine Tower of Caelid: Center",
        grace_entity_id: 34131952,
        flag_id: 73441,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Divine Tower of Caelid: Basement",
        grace_entity_id: 34131951,
        flag_id: 73440,
        dlc: false,
    },
    Grace {
        main_area: "Greyoll's Dragonbarrow",
        name: "Isolated Divine Tower",
        grace_entity_id: 34151950,
        flag_id: 73460,
        dlc: false,
    },
    Grace {
        main_area: "Forbidden Lands",
        name: "Forbidden Lands",
        grace_entity_id: 1047511950,
        flag_id: 76500,
        dlc: false,
    },
    Grace {
        main_area: "Forbidden Lands",
        name: "Grand Lift of Rold",
        grace_entity_id: 1049531951,
        flag_id: 76502,
        dlc: false,
    },
    Grace {
        main_area: "Forbidden Lands",
        name: "Hidden Path to the Haligtree",
        grace_entity_id: 30201950,
        flag_id: 73020,
        dlc: false,
    },
    Grace {
        main_area: "Forbidden Lands",
        name: "Divine Tower of East Altus: Gate",
        grace_entity_id: 34141950,
        flag_id: 73450,
        dlc: false,
    },
    Grace {
        main_area: "Forbidden Lands",
        name: "Divine Tower of East Altus",
        grace_entity_id: 34141951,
        flag_id: 73451,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Zamor Ruins",
        grace_entity_id: 1049531950,
        flag_id: 76501,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Ancient Snow Valley Ruins",
        grace_entity_id: 1051561950,
        flag_id: 76503,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Freezing Lake",
        grace_entity_id: 1052571950,
        flag_id: 76504,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "First Church of Marika",
        grace_entity_id: 1054551950,
        flag_id: 76505,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Whiteridge Road",
        grace_entity_id: 1052561950,
        flag_id: 76520,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Snow Valley Ruins Overlook",
        grace_entity_id: 1051571950,
        flag_id: 76521,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Castle Sol Main Gate",
        grace_entity_id: 1051571951,
        flag_id: 76522,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Church of the Eclipse",
        grace_entity_id: 1051571952,
        flag_id: 76523,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Castle Sol Rooftop",
        grace_entity_id: 1051571953,
        flag_id: 76524,
        dlc: false,
    },
    Grace {
        main_area: "Mountaintops of the Giants",
        name: "Spiritcaller's Cave",
        grace_entity_id: 31221950,
        flag_id: 73122,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Giant's Gravepost",
        grace_entity_id: 1052541950,
        flag_id: 76506,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Church of Repose",
        grace_entity_id: 1051531950,
        flag_id: 76507,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Foot of the Forge",
        grace_entity_id: 1052531950,
        flag_id: 76508,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Fire Giant",
        grace_entity_id: 1053521950,
        flag_id: 76509,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Forge of the Giants",
        grace_entity_id: 1054531950,
        flag_id: 76510,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Giants' Mountaintop Catacombs",
        grace_entity_id: 30181950,
        flag_id: 73018,
        dlc: false,
    },
    Grace {
        main_area: "Flame Peak",
        name: "Giant-Conquering Hero's Grave",
        grace_entity_id: 30171950,
        flag_id: 73017,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Consecrated Snowfield",
        grace_entity_id: 1049541950,
        flag_id: 76550,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Inner Consecrated Snowfield",
        grace_entity_id: 1049551950,
        flag_id: 76551,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Ordina, Liturgical Town",
        grace_entity_id: 1048571950,
        flag_id: 76652,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Apostate Derelict",
        grace_entity_id: 1047581950,
        flag_id: 76653,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Consecrated Snowfield Catacombs",
        grace_entity_id: 30191950,
        flag_id: 73019,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Cave of the Forlorn",
        grace_entity_id: 31121950,
        flag_id: 73112,
        dlc: false,
    },
    Grace {
        main_area: "Consecrated Snowfield",
        name: "Yelough Anix Tunnel",
        grace_entity_id: 32111950,
        flag_id: 73211,
        dlc: false,
    },
    Grace {
        main_area: "Miquella's Haligtree",
        name: "Haligtree Canopy",
        grace_entity_id: 15001956,
        flag_id: 71506,
        dlc: false,
    },
    Grace {
        main_area: "Miquella's Haligtree",
        name: "Haligtree Town",
        grace_entity_id: 15001957,
        flag_id: 71507,
        dlc: false,
    },
    Grace {
        main_area: "Miquella's Haligtree",
        name: "Haligtree Town Plaza",
        grace_entity_id: 15001958,
        flag_id: 71508,
        dlc: false,
    },
    Grace {
        main_area: "Miquella's Haligtree",
        name: "Haligtree Promenade",
        grace_entity_id: 15001955,
        flag_id: 71505,
        dlc: false,
    },
    Grace {
        main_area: "Elphael, Brace of the Haligtree",
        name: "Prayer Room",
        grace_entity_id: 15001951,
        flag_id: 71501,
        dlc: false,
    },
    Grace {
        main_area: "Elphael, Brace of the Haligtree",
        name: "Elphael Inner Wall",
        grace_entity_id: 15001952,
        flag_id: 71502,
        dlc: false,
    },
    Grace {
        main_area: "Elphael, Brace of the Haligtree",
        name: "Drainage Channel",
        grace_entity_id: 15001953,
        flag_id: 71503,
        dlc: false,
    },
    Grace {
        main_area: "Elphael, Brace of the Haligtree",
        name: "Haligtree Roots",
        grace_entity_id: 15001954,
        flag_id: 71504,
        dlc: false,
    },
    Grace {
        main_area: "Elphael, Brace of the Haligtree",
        name: "Malenia, Goddess of Rot",
        grace_entity_id: 15001950,
        flag_id: 71500,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River",
        name: "Ainsel River Well Depths",
        grace_entity_id: 12011951,
        flag_id: 71211,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River",
        name: "Ainsel River Sluice Gate",
        grace_entity_id: 12011952,
        flag_id: 71212,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River",
        name: "Ainsel River Downstream",
        grace_entity_id: 12011953,
        flag_id: 71213,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River",
        name: "Dragonkin Soldier of Nokstella",
        grace_entity_id: 12011950,
        flag_id: 71210,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River",
        name: "Astel, Naturalborn of the Void",
        grace_entity_id: 12041950,
        flag_id: 71240,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River Main",
        name: "Ainsel River Main",
        grace_entity_id: 12011954,
        flag_id: 71214,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River Main",
        name: "Nokstella, Eternal City",
        grace_entity_id: 12011955,
        flag_id: 71215,
        dlc: false,
    },
    Grace {
        main_area: "Ainsel River Main",
        name: "Nokstella Waterfall Basin",
        grace_entity_id: 12011959,
        flag_id: 71219,
        dlc: false,
    },
    Grace {
        main_area: "Lake of Rot",
        name: "Lake of Rot Shoreside",
        grace_entity_id: 12011956,
        flag_id: 71216,
        dlc: false,
    },
    Grace {
        main_area: "Lake of Rot",
        name: "Grand Cloister",
        grace_entity_id: 12011958,
        flag_id: 71218,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Nokron, Eternal City",
        grace_entity_id: 12071951,
        flag_id: 71271,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Mimic Tear",
        grace_entity_id: 12021951,
        flag_id: 71221,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Ancestral Woods",
        grace_entity_id: 12021956,
        flag_id: 71224,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Night's Sacred Ground",
        grace_entity_id: 12021958,
        flag_id: 71226,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Aqueduct-Facing Cliffs",
        grace_entity_id: 12021957,
        flag_id: 71225,
        dlc: false,
    },
    Grace {
        main_area: "Nokron, Eternal City",
        name: "Great Waterfall Basin",
        grace_entity_id: 12021950,
        flag_id: 71220,
        dlc: false,
    },
    Grace {
        main_area: "Siofra River",
        name: "Siofra River Well Depths",
        grace_entity_id: 12071950,
        flag_id: 71270,
        dlc: false,
    },
    Grace {
        main_area: "Siofra River",
        name: "Siofra River Bank",
        grace_entity_id: 12021953,
        flag_id: 71222,
        dlc: false,
    },
    Grace {
        main_area: "Siofra River",
        name: "Worshippers' Woods",
        grace_entity_id: 12021954,
        flag_id: 71223,
        dlc: false,
    },
    Grace {
        main_area: "Siofra River",
        name: "Below the Well",
        grace_entity_id: 12021959,
        flag_id: 71227,
        dlc: false,
    },
    Grace {
        main_area: "Mohgwyn Palace",
        name: "Palace Approach Ledge-Road",
        grace_entity_id: 12051951,
        flag_id: 71251,
        dlc: false,
    },
    Grace {
        main_area: "Mohgwyn Palace",
        name: "Dynasty Mausoleum Entrance",
        grace_entity_id: 12051952,
        flag_id: 71252,
        dlc: false,
    },
    Grace {
        main_area: "Mohgwyn Palace",
        name: "Dynasty Mausoleum Midpoint",
        grace_entity_id: 12051953,
        flag_id: 71253,
        dlc: false,
    },
    Grace {
        main_area: "Mohgwyn Palace",
        name: "Cocoon of the Empyrean",
        grace_entity_id: 12051950,
        flag_id: 71250,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "Root-Facing Cliffs",
        grace_entity_id: 12031951,
        flag_id: 71231,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "Great Waterfall Crest",
        grace_entity_id: 12031952,
        flag_id: 71232,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "Deeproot Depths",
        grace_entity_id: 12031953,
        flag_id: 71233,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "The main_arealess Eternal City",
        grace_entity_id: 12031954,
        flag_id: 71234,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "Across the Roots",
        grace_entity_id: 12031955,
        flag_id: 71235,
        dlc: false,
    },
    Grace {
        main_area: "Deeproot Depths",
        name: "Prince of Death's Throne",
        grace_entity_id: 12031950,
        flag_id: 71230,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Crumbling Beast Grave",
        grace_entity_id: 13001953,
        flag_id: 71303,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Crumbling Beast Grave Depths",
        grace_entity_id: 13001954,
        flag_id: 71304,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Tempest-Facing Balcony",
        grace_entity_id: 13001955,
        flag_id: 71305,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragon Temple",
        grace_entity_id: 13001956,
        flag_id: 71306,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragon Temple Transept",
        grace_entity_id: 13001957,
        flag_id: 71307,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragon Temple Altar",
        grace_entity_id: 13001952,
        flag_id: 71302,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragon Temple Lift",
        grace_entity_id: 13001958,
        flag_id: 71308,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragon Temple Rooftop",
        grace_entity_id: 13001959,
        flag_id: 71309,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Beside the Great Bridge",
        grace_entity_id: 13001960,
        flag_id: 71310,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Maliketh, the Black Blade",
        grace_entity_id: 13001950,
        flag_id: 71300,
        dlc: false,
    },
    Grace {
        main_area: "Crumbling Farum Azula",
        name: "Dragonlord Placidusax",
        grace_entity_id: 13001951,
        flag_id: 71301,
        dlc: false,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Gravesite Plain",
        grace_entity_id: 2046401950,
        flag_id: 76800,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Scorched Ruins",
        grace_entity_id: 2047411950,
        flag_id: 76801,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Three-Path Cross",
        grace_entity_id: 2046421950,
        flag_id: 76802,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Greatbridge, North",
        grace_entity_id: 2046441950,
        flag_id: 76805,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Main Gate Cross",
        grace_entity_id: 2045421950,
        flag_id: 76803,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Cliffroad Terminus",
        grace_entity_id: 2045411950,
        flag_id: 76804,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Castle Front",
        grace_entity_id: 2047441950,
        flag_id: 76813,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Pillar Path Cross",
        grace_entity_id: 2048431950,
        flag_id: 76810,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Pillar Path Waypoint",
        grace_entity_id: 2048421950,
        flag_id: 76811,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Ellac River Cave",
        grace_entity_id: 2047431950,
        flag_id: 76812,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Ellac River Downstream",
        grace_entity_id: 2047411951,
        flag_id: 76830,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Fog Rift Catacombs",
        grace_entity_id: 40001950,
        flag_id: 74000,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Belurat Gaol",
        grace_entity_id: 41001950,
        flag_id: 74100,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Ruined Forge Lava Intake",
        grace_entity_id: 42001950,
        flag_id: 74200,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Rivermouth Cave",
        grace_entity_id: 43001950,
        flag_id: 74300,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Dragon's Pit",
        grace_entity_id: 43011950,
        flag_id: 74301,
        dlc: true,
    },
    Grace {
        main_area: "Gravesite Plain",
        name: "Dragon's Pit Terminus",
        grace_entity_id: 43011951,
        flag_id: 74351,
        dlc: true,
    },
    Grace {
        main_area: "Castle Ensis",
        name: "Castle Ensis Checkpoint",
        grace_entity_id: 2047441951,
        flag_id: 76821,
        dlc: true,
    },
    Grace {
        main_area: "Castle Ensis",
        name: "Castle-Lord's Chamber",
        grace_entity_id: 2048441951,
        flag_id: 76822,
        dlc: true,
    },
    Grace {
        main_area: "Castle Ensis",
        name: "Ensis Moongazing Grounds",
        grace_entity_id: 2048441950,
        flag_id: 76823,
        dlc: true,
    },
    Grace {
        main_area: "Cerulean Coast",
        name: "Cerulean Coast",
        grace_entity_id: 2048391950,
        flag_id: 76831,
        dlc: true,
    },
    Grace {
        main_area: "Cerulean Coast",
        name: "Cerulean Coast West",
        grace_entity_id: 2046391950,
        flag_id: 76832,
        dlc: true,
    },
    Grace {
        main_area: "Cerulean Coast",
        name: "Cerulean Coast Cross",
        grace_entity_id: 2048371950,
        flag_id: 76835,
        dlc: true,
    },
    Grace {
        main_area: "Cerulean Coast",
        name: "The Fissure",
        grace_entity_id: 2047351950,
        flag_id: 76833,
        dlc: true,
    },
    Grace {
        main_area: "Cerulean Coast",
        name: "Finger Ruins of Rhia",
        grace_entity_id: 2050381950,
        flag_id: 76834,
        dlc: true,
    },
    Grace {
        main_area: "Charo's Hidden Grave",
        name: "Charo's Hidden Grave",
        grace_entity_id: 2048391951,
        flag_id: 76841,
        dlc: true,
    },
    Grace {
        main_area: "Charo's Hidden Grave",
        name: "Lamenter's Gaol",
        grace_entity_id: 41021950,
        flag_id: 74102,
        dlc: true,
    },
    Grace {
        main_area: "Stone Coffin Fissure",
        name: "Stone Coffin Fissure",
        grace_entity_id: 22001951,
        flag_id: 72201,
        dlc: true,
    },
    Grace {
        main_area: "Stone Coffin Fissure",
        name: "Fissure Cross",
        grace_entity_id: 22001952,
        flag_id: 72202,
        dlc: true,
    },
    Grace {
        main_area: "Stone Coffin Fissure",
        name: "Fissure Waypoint",
        grace_entity_id: 22001953,
        flag_id: 72203,
        dlc: true,
    },
    Grace {
        main_area: "Stone Coffin Fissure",
        name: "Fissure Depths",
        grace_entity_id: 22001954,
        flag_id: 72204,
        dlc: true,
    },
    Grace {
        main_area: "Stone Coffin Fissure",
        name: "Garden of Deep Purple",
        grace_entity_id: 22001950,
        flag_id: 72200,
        dlc: true,
    },
    Grace {
        main_area: "Foot of the Jagged Peak",
        name: "Grand Altar of Dragon Communion",
        grace_entity_id: 2049391950,
        flag_id: 76840,
        dlc: true,
    },
    Grace {
        main_area: "Foot of the Jagged Peak",
        name: "Foot of the Jagged Peak",
        grace_entity_id: 2052401950,
        flag_id: 76850,
        dlc: true,
    },
    Grace {
        main_area: "Jagged Peak",
        name: "Jagged Peak Mountainside",
        grace_entity_id: 2053391950,
        flag_id: 76851,
        dlc: true,
    },
    Grace {
        main_area: "Jagged Peak",
        name: "Jagged Peak Summit",
        grace_entity_id: 2054391950,
        flag_id: 76852,
        dlc: true,
    },
    Grace {
        main_area: "Jagged Peak",
        name: "Rest of the Dread Dragon",
        grace_entity_id: 2055391950,
        flag_id: 76853,
        dlc: true,
    },
    Grace {
        main_area: "Belurat, Tower Settlement",
        name: "Belurat, Tower Settlement",
        grace_entity_id: 20001951,
        flag_id: 72001,
        dlc: true,
    },
    Grace {
        main_area: "Belurat, Tower Settlement",
        name: "Small Private Altar",
        grace_entity_id: 20001952,
        flag_id: 72002,
        dlc: true,
    },
    Grace {
        main_area: "Belurat, Tower Settlement",
        name: "Stagefront",
        grace_entity_id: 20001953,
        flag_id: 72003,
        dlc: true,
    },
    Grace {
        main_area: "Belurat, Tower Settlement",
        name: "Theatre of the Divine Beast",
        grace_entity_id: 20001950,
        flag_id: 72000,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "Enir-Ilim: Outer Wall",
        grace_entity_id: 20011952,
        flag_id: 72012,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "First Rise",
        grace_entity_id: 20011953,
        flag_id: 72013,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "Spiral Rise",
        grace_entity_id: 20011954,
        flag_id: 72014,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "Cleansing Chamber Anteroom",
        grace_entity_id: 20011955,
        flag_id: 72015,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "Divine Gate Front Staircase",
        grace_entity_id: 20011956,
        flag_id: 72016,
        dlc: true,
    },
    Grace {
        main_area: "Enir-Ilim",
        name: "Gate of Divinity",
        grace_entity_id: 20011950,
        flag_id: 72010,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Viaduct Minor Tower",
        grace_entity_id: 2047471950,
        flag_id: 76940,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Rauh Ancient Ruins, East",
        grace_entity_id: 2046471950,
        flag_id: 76941,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Rauh Ancient Ruins, West",
        grace_entity_id: 2045451951,
        flag_id: 76942,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Ancient Ruins, Grand Stairway",
        grace_entity_id: 2044451950,
        flag_id: 76944,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Church of the Bud, Main Entrance",
        grace_entity_id: 2044461950,
        flag_id: 76943,
        dlc: true,
    },
    Grace {
        main_area: "Ancient Ruins of Rauh",
        name: "Church of the Bud",
        grace_entity_id: 2044451951,
        flag_id: 76945,
        dlc: true,
    },
    Grace {
        main_area: "Rauh Base",
        name: "Ancient Ruins Base",
        grace_entity_id: 2048471950,
        flag_id: 76912,
        dlc: true,
    },
    Grace {
        main_area: "Rauh Base",
        name: "Temple Town Ruins",
        grace_entity_id: 2045461950,
        flag_id: 76913,
        dlc: true,
    },
    Grace {
        main_area: "Rauh Base",
        name: "Ravine North",
        grace_entity_id: 2045471950,
        flag_id: 76914,
        dlc: true,
    },
    Grace {
        main_area: "Rauh Base",
        name: "Scorpion River Catacombs",
        grace_entity_id: 40011950,
        flag_id: 74001,
        dlc: true,
    },
    Grace {
        main_area: "Rauh Base",
        name: "Taylew's Ruined Forge",
        grace_entity_id: 42031950,
        flag_id: 74203,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Highroad Cross",
        grace_entity_id: 2048451950,
        flag_id: 76900,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Scadu Altus, West",
        grace_entity_id: 2047451950,
        flag_id: 76907,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Moorth Ruins",
        grace_entity_id: 2049441950,
        flag_id: 76902,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Moorth Highway, South",
        grace_entity_id: 2049431950,
        flag_id: 76908,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Fort of Reprimand",
        grace_entity_id: 2049431951,
        flag_id: 76909,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Behind the Fort of Reprimand",
        grace_entity_id: 2049431952,
        flag_id: 76910,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Scaduview Cross",
        grace_entity_id: 2050431950,
        flag_id: 76911,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Bonny Village",
        grace_entity_id: 2049441951,
        flag_id: 76903,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Bridge Leading to the Village",
        grace_entity_id: 2051441950,
        flag_id: 76904,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Church District Highroad",
        grace_entity_id: 2051471950,
        flag_id: 76905,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Cathedral of Manus Metyr",
        grace_entity_id: 2051451950,
        flag_id: 76906,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Finger Birthing Grounds",
        grace_entity_id: 25001950,
        flag_id: 72500,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Castle Watering Hole",
        grace_entity_id: 2049471950,
        flag_id: 76916,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Recluses' River Upstream",
        grace_entity_id: 2050451950,
        flag_id: 76917,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Recluses' River Downstream",
        grace_entity_id: 2050441950,
        flag_id: 76918,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Darklight Catacombs",
        grace_entity_id: 40021950,
        flag_id: 74002,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Bonny Gaol",
        grace_entity_id: 41011950,
        flag_id: 74101,
        dlc: true,
    },
    Grace {
        main_area: "Scadu Altus",
        name: "Ruined Forge of Starfall Past",
        grace_entity_id: 42021950,
        flag_id: 74202,
        dlc: true,
    },
    Grace {
        main_area: "Abyssal Woods",
        name: "Forsaken Graveyard",
        grace_entity_id: 2052431950,
        flag_id: 76862,
        dlc: true,
    },
    Grace {
        main_area: "Abyssal Woods",
        name: "Woodland Trail",
        grace_entity_id: 2051421950,
        flag_id: 76863,
        dlc: true,
    },
    Grace {
        main_area: "Abyssal Woods",
        name: "Church Ruins",
        grace_entity_id: 2053411950,
        flag_id: 76864,
        dlc: true,
    },
    Grace {
        main_area: "Abyssal Woods",
        name: "Abyssal Woods",
        grace_entity_id: 2050421950,
        flag_id: 76860,
        dlc: true,
    },
    Grace {
        main_area: "Abyssal Woods",
        name: "Divided Falls",
        grace_entity_id: 2048431951,
        flag_id: 76861,
        dlc: true,
    },
    Grace {
        main_area: "Midra's Manse",
        name: "Manse Hall",
        grace_entity_id: 28001951,
        flag_id: 72801,
        dlc: true,
    },
    Grace {
        main_area: "Midra's Manse",
        name: "Midra's Library",
        grace_entity_id: 28001952,
        flag_id: 72802,
        dlc: true,
    },
    Grace {
        main_area: "Midra's Manse",
        name: "Second Floor Chamber",
        grace_entity_id: 28001953,
        flag_id: 72803,
        dlc: true,
    },
    Grace {
        main_area: "Midra's Manse",
        name: "Discussion Chamber",
        grace_entity_id: 28001950,
        flag_id: 72800,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep",
        name: "Shadow Keep Main Gate",
        grace_entity_id: 21001952,
        flag_id: 72102,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep",
        name: "Main Gate Plaza",
        grace_entity_id: 21001951,
        flag_id: 72101,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep, Church District",
        name: "Church District Entrance",
        grace_entity_id: 21001956,
        flag_id: 72106,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep, Church District",
        name: "Sunken Chapel",
        grace_entity_id: 21001957,
        flag_id: 72107,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep, Church District",
        name: "Tree-Worship Passage",
        grace_entity_id: 21001958,
        flag_id: 72108,
        dlc: true,
    },
    Grace {
        main_area: "Shadow Keep, Church District",
        name: "Tree-Worship Sanctum",
        grace_entity_id: 21001959,
        flag_id: 72109,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Storehouse, First Floor",
        grace_entity_id: 21011951,
        flag_id: 72111,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Storehouse, Fourth Floor",
        grace_entity_id: 21011952,
        flag_id: 72112,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Storehouse, Seventh Floor",
        grace_entity_id: 21011953,
        flag_id: 72113,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Dark Chamber Entrance",
        grace_entity_id: 21011954,
        flag_id: 72114,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Storehouse, Back Section",
        grace_entity_id: 21011956,
        flag_id: 72116,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Storehouse, Loft",
        grace_entity_id: 21011957,
        flag_id: 72117,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "West Rampart",
        grace_entity_id: 21021951,
        flag_id: 72120,
        dlc: true,
    },
    Grace {
        main_area: "Specimen Storehouse",
        name: "Messmer's Dark Chamber",
        grace_entity_id: 21011950,
        flag_id: 72110,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Scaduview",
        grace_entity_id: 2049481950,
        flag_id: 76930,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Shadow Keep, Back Gate",
        grace_entity_id: 2049481951,
        flag_id: 76931,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Scadutree Base",
        grace_entity_id: 2050481951,
        flag_id: 76960,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Hinterland",
        grace_entity_id: 2050481950,
        flag_id: 76935,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Hinterland Bridge",
        grace_entity_id: 2051481951,
        flag_id: 76937,
        dlc: true,
    },
    Grace {
        main_area: "Scaduview",
        name: "Fingerstone Hill",
        grace_entity_id: 2051481950,
        flag_id: 76936,
        dlc: true,
    },
];
