use serde::{Deserialize, Serialize};

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize, Debug, Default, Clone)]
pub struct ErAttachConfig {
    pub NoDeath:                   bool,
    pub NoDamage:                  bool,
    pub InfinitePoise:             bool,
    pub OneShot:                   bool,
    pub RuneArc:                   bool,
    pub SetRfbsOnLoad:             bool,
    pub NoRuneLossOnDeath:         bool,
    pub NoTimePassOnDeath:         bool,
    pub Hidden:                    bool,
    pub Silent:                    bool,
    pub InfiniteStamina:           bool,
    pub InfiniteFp:                bool,
    pub InfiniteConsumables:       bool,
    pub InfiniteArrows:            bool,
    pub TorrentAnywhere:           bool,
    pub TorrentNoDeath:            bool,
    pub FpsCap:                    Option<f32>,
    pub GameSpeed:                 Option<f32>,
    pub DisableLogos:              bool,
    pub MuteMusic:                 bool,
    pub DisableAreaWelcomeMessage: bool,
    pub StutterFix:                bool,
    pub MapInCombat:               bool,
    pub TravelInDungeons:          bool,
    pub DrawHitboxes:              bool,
    pub ShowAllGraces:             bool,
    pub ShowAllMaps:               bool,
    pub DisableRoll:               bool,
    pub DisableJump:               bool,
    pub DisableBackstep:           bool,
}
