use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Default, Clone)]
pub struct ErAttachConfig {
    pub no_death:                     bool,
    pub no_damage:                    bool,
    pub infinite_poise:               bool,
    pub one_shot:                     bool,
    pub rune_arc:                     bool,
    pub rfbs_on_load:                 bool,
    pub hidden:                       bool,
    pub silent:                       bool,
    pub infinite_stamina:             bool,
    pub infinite_fp:                  bool,
    pub infinite_consumables:         bool,
    pub infinite_arrows:              bool,
    pub torrent_anywhere:             bool,
    pub torrent_no_death:             bool,
    pub fps_cap:                      Option<f32>,
    pub game_speed:                   Option<f32>,
    pub disable_logos:                bool,
    pub mute_music:                   bool,
    pub disable_area_welcome_message: bool,
    pub stutter_fix:                  bool,
    pub map_in_combat:                bool,
    pub travel_in_dungeon:            bool,
    pub draw_hitboxes:                bool,
    pub show_all_graces:              bool,
    pub show_all_maps:                bool,
    pub disable_roll:                 bool,
    pub disable_jump:                 bool,
    pub disable_backstep:             bool,
}
