max_width = 100
use_small_heuristics = "Off"
fn_call_width = 80
attr_fn_like_width = 80
array_width = 60
chain_width = 60
single_line_if_else_max_width = 80

binop_separator = "Front"
brace_style = "SameLineWhere"
combine_control_expr = false
edition = "2024"
enum_discrim_align_threshold = 99
fn_params_layout = "Tall"
fn_single_line = false
force_multiline_blocks = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
float_literal_trailing_zero = "Always"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Preserve"
match_arm_indent = true
unstable_features = true
imports_granularity = "One"
newline_style = "Unix"
overflow_delimited_expr = true
group_imports = "One"
short_array_element_width_threshold = 5
struct_field_align_threshold = 99
struct_lit_single_line = false
trailing_semicolon = false
where_single_line = true
