pub const OFFSETS_1_8_0: ModuleOffsets = ModuleOffsets {
    base_ptrs:        BasePointers {
        world_chr_man:              0x3cd9998,
        field_area:                 0x3cdcb80,
        game_man:                   0x3cdd2c8,
        game_data_man:              0x3cd1948,
        menu_man:                   0x3cdf140,
        world_area_time_impl:       0x3cdccb0,
        cs_emk_system:              0x3cdb580,
        virtual_mem_flag:           0x3cdbdf8,
        damage_manager:             0x3cd9d68,
        map_item_man_impl:          0x3cdb400,
        dl_user_input_manager_impl: 0x45b1918,
        cs_flipper_imp:             0x44fd2c8,
        cs_dlc_imp:                 0x3cfa3f8,
        lock_tgt_man_imp:           0x3cddba0,
    },
    functions:        Functions {
        grace_warp:                     0x5951e0,
        block_warp:                     0x5eb330,
        get_player_item_quantity_by_id: 0x773500,
        item_spawn:                     0x55c1a0,
        give_runes:                     0x25c670,
        get_event:                      0x5ecc60,
        set_event:                      0x5ed450,
        set_speffect:                   0x3e69c0,
        remove_speffect:                0x4f2e00,
        get_chr_ins_by_entity_id:       0x503c30,
        emevd_switch:                   0x563930,
        emk_event_ins_ctor:             0x57ddc0,
        external_event_temp_ctor:       0x1ff7d00,
        execute_talk_command:           0xe628c0,
        add_cool_time:                  0x2c4850,
    },
    hooks:            Hooks {
        locked_target_pointer: 0x7078c6,
        target_no_stagger:     0x47b0e5,
        player_no_grab:        0x44679b,
        player_infinite_poise: 0x442bb0,
        warp_coord_write:      0x66c2aa,
        warp_angle_write:      0x66c28a,
        get_force_act_idx:     0x5757732,
        set_requested_action:  0x404f92,
        no_time_pass_on_death: 0x5efb77,
    },
    patches:          Patches {
        no_logo:                     0xadb0fd,
        fps_cap:                     0xe4167f,
        mute_music:                  0xd88d0a,
        pause_world:                 0xac78e5,
        torrent_disabled_underworld: 0xcba2fa,
        whistle_disabled:            0x6f6abf,
        open_map:                    0x7dbeba,
        close_map:                   0x9a14fa,
        can_fast_travel:             0x7b2110,
        no_rune_loss_on_death:       0x5ef995,
    },
    data:             Data {
        chr_dbg_flags: 0x3cd9b97,
        map_dbg_flags: 0x3ce0940,
    },
    external_fn_ptrs: ExternalFunctionPointers {
        kernel32_create_thread:  0x495c734,
        kernel32_close_handle:   0x495c5e4,
        kernel32_load_library_w: 0x495c774,
    },
};
