pub const OFFSETS_2_0_1: ModuleOffsets = ModuleOffsets {
    base_ptrs:        BasePointers {
        world_chr_man:              0x3cdcdd8,
        field_area:                 0x3cdffc0,
        game_man:                   0x3ce0708,
        game_data_man:              0x3cd4d88,
        menu_man:                   0x3ce2580,
        world_area_time_impl:       0x3ce00f0,
        cs_emk_system:              0x3cde9c0,
        virtual_mem_flag:           0x3cdf238,
        damage_manager:             0x3cdd1a8,
        map_item_man_impl:          0x3cde840,
        dl_user_input_manager_impl: 0x45b4d48,
        cs_flipper_imp:             0x4500708,
        cs_dlc_imp:                 0x3cfd838,
        lock_tgt_man_imp:           0x3ce0fe0,
    },
    functions:        Functions {
        grace_warp:                     0x595800,
        block_warp:                     0x5ec2f0,
        get_player_item_quantity_by_id: 0x774890,
        item_spawn:                     0x55c760,
        give_runes:                     0x25c7a0,
        get_event:                      0x5edc20,
        set_event:                      0x5ee410,
        set_speffect:                   0x3e6af0,
        remove_speffect:                0x4f32b0,
        get_chr_ins_by_entity_id:       0x5041f0,
        emevd_switch:                   0x563ef0,
        emk_event_ins_ctor:             0x57e380,
        external_event_temp_ctor:       0x1ffae70,
        execute_talk_command:           0xe65800,
        add_cool_time:                  0x2c4980,
    },
    hooks:            Hooks {
        locked_target_pointer: 0x708c56,
        target_no_stagger:     0x47b3c5,
        player_no_grab:        0x446a7b,
        player_infinite_poise: 0x442dc0,
        warp_coord_write:      0x66d4da,
        warp_angle_write:      0x66d4ba,
        get_force_act_idx:     0x55611fb,
        set_requested_action:  0x4050c2,
        no_time_pass_on_death: 0x5f0b37,
    },
    patches:          Patches {
        no_logo:                     0xaddf7d,
        fps_cap:                     0xe4482f,
        mute_music:                  0xd8bdda,
        pause_world:                 0xaca765,
        torrent_disabled_underworld: 0xcbd20a,
        whistle_disabled:            0x6f7e4f,
        open_map:                    0x7dd2aa,
        close_map:                   0x9a383a,
        can_fast_travel:             0x7b34a0,
        no_rune_loss_on_death:       0x5f0955,
    },
    data:             Data {
        chr_dbg_flags: 0x3cdcfe8,
        map_dbg_flags: 0x3ce3d80,
    },
    external_fn_ptrs: ExternalFunctionPointers {
        kernel32_create_thread:  0x495f6c4,
        kernel32_close_handle:   0x495f58c,
        kernel32_load_library_w: 0x495f704,
    },
};
