use crate::resources::map_ids::MapId;

pub struct Bonfire {
    pub name:       &'static str,
    pub main_area:  &'static str,
    pub bonfire_id: u32,
    pub map_id:     MapId,
}

pub const BONFIRES: &[Bonfire; 77] = &[
    Bonfire {
        name:       "Fire Keeper's Dwelling",
        main_area:  "Things Betwixt",
        bonfire_id: 2650,
        map_id:     MapId::ThingsBetwixed,
    },
    Bonfire {
        name:       "Far Fire",
        main_area:  "Majula",
        bonfire_id: 4650,
        map_id:     MapId::Majula,
    },
    Bonfire {
        name:       "Crestfallen's Retreat",
        main_area:  "Forest of Fallen Giants",
        bonfire_id: 10670,
        map_id:     MapId::ForestOfFallenGiants,
    },
    Bonfire {
        name:       "Cardinal Tower",
        main_area:  "Forest of Fallen Giants",
        bonfire_id: 10655,
        map_id:     MapId::ForestOfFallenGiants,
    },
    Bonfire {
        name:       "Soldier's Rest",
        main_area:  "Forest of Fallen Giants",
        bonfire_id: 10660,
        map_id:     MapId::ForestOfFallenGiants,
    },
    Bonfire {
        name:       "The Place Unbeknownst",
        main_area:  "Forest of Fallen Giants",
        bonfire_id: 10675,
        map_id:     MapId::ForestOfFallenGiants,
    },
    Bonfire {
        name:       "Heide's Ruin",
        main_area:  "Heide's Tower of Flame",
        bonfire_id: 31655,
        map_id:     MapId::HeidesTowerOfFlame,
    },
    Bonfire {
        name:       "Tower of Flame",
        main_area:  "Heide's Tower of Flame",
        bonfire_id: 31650,
        map_id:     MapId::HeidesTowerOfFlame,
    },
    Bonfire {
        name:       "Cathedral of Blue",
        main_area:  "Heide's Tower of Flame",
        bonfire_id: 31660,
        map_id:     MapId::HeidesTowerOfFlame,
    },
    Bonfire {
        name:       "Unseen Path to Heide's",
        main_area:  "No-man's Wharf",
        bonfire_id: 18650,
        map_id:     MapId::NoMansWharf,
    },
    Bonfire {
        name:       "Exile Holding Cells",
        main_area:  "The Lost Bastille",
        bonfire_id: 16655,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "McDuff's Workshop",
        main_area:  "The Lost Bastille",
        bonfire_id: 16670,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "Servant's Quarters",
        main_area:  "The Lost Bastille",
        bonfire_id: 16675,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "Straid's Cell",
        main_area:  "The Lost Bastille",
        bonfire_id: 16650,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "The Tower Apart",
        main_area:  "The Lost Bastille",
        bonfire_id: 16660,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "The Saltfort",
        main_area:  "Sinners' Rise",
        bonfire_id: 16685,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "Upper Ramparts",
        main_area:  "Belfry Luna",
        bonfire_id: 16665,
        map_id:     MapId::TheLostBastille,
    },
    Bonfire {
        name:       "Undead Refuge",
        main_area:  "Huntsman's Copse",
        bonfire_id: 23650,
        map_id:     MapId::HuntsmansCorpse,
    },
    Bonfire {
        name:       "Bridge Approach",
        main_area:  "Huntsman's Copse",
        bonfire_id: 23655,
        map_id:     MapId::HuntsmansCorpse,
    },
    Bonfire {
        name:       "Undead Lockaway",
        main_area:  "Huntsman's Copse",
        bonfire_id: 23660,
        map_id:     MapId::HuntsmansCorpse,
    },
    Bonfire {
        name:       "Undead Purgatory",
        main_area:  "Undead Purgatory",
        bonfire_id: 23665,
        map_id:     MapId::HuntsmansCorpse,
    },
    Bonfire {
        name:       "Poison Pool",
        main_area:  "Harvest Valley",
        bonfire_id: 17665,
        map_id:     MapId::HarvestValley,
    },
    Bonfire {
        name:       "The Mines",
        main_area:  "Harvest Valley",
        bonfire_id: 17650,
        map_id:     MapId::HarvestValley,
    },
    Bonfire {
        name:       "Lower Earthen Peak",
        main_area:  "Earthen Peak",
        bonfire_id: 17655,
        map_id:     MapId::HarvestValley,
    },
    Bonfire {
        name:       "Central Earthen Peak",
        main_area:  "Earthen Peak",
        bonfire_id: 17670,
        map_id:     MapId::HarvestValley,
    },
    Bonfire {
        name:       "Upper Earthen Peak",
        main_area:  "Earthen Peak",
        bonfire_id: 17675,
        map_id:     MapId::HarvestValley,
    },
    Bonfire {
        name:       "Threshold Bridge",
        main_area:  "Iron Keep",
        bonfire_id: 19655,
        map_id:     MapId::IronKeep,
    },
    Bonfire {
        name:       "Ironhearth Hall",
        main_area:  "Iron Keep",
        bonfire_id: 19650,
        map_id:     MapId::IronKeep,
    },
    Bonfire {
        name:       "Eygil's Idol",
        main_area:  "Iron Keep",
        bonfire_id: 19660,
        map_id:     MapId::IronKeep,
    },
    Bonfire {
        name:       "Belfry Sol Approach",
        main_area:  "Belfry Sol",
        bonfire_id: 19665,
        map_id:     MapId::IronKeep,
    },
    Bonfire {
        name:       "Old Akelarre",
        main_area:  "Shaded Woods",
        bonfire_id: 29650,
        map_id:     MapId::PathToShadedWoods,
    },
    Bonfire {
        name:       "Ruined Fork Road",
        main_area:  "Shaded Woods",
        bonfire_id: 32655,
        map_id:     MapId::ShadedWoods,
    },
    Bonfire {
        name:       "Shaded Ruins",
        main_area:  "Shaded Woods",
        bonfire_id: 32660,
        map_id:     MapId::ShadedWoods,
    },
    Bonfire {
        name:       "Gyrm's Respite",
        main_area:  "Doors of Pharros",
        bonfire_id: 33655,
        map_id:     MapId::DoorsOfPharros,
    },
    Bonfire {
        name:       "Ordeal's End",
        main_area:  "Doors of Pharros",
        bonfire_id: 33660,
        map_id:     MapId::DoorsOfPharros,
    },
    Bonfire {
        name:       "Royal Army Campsite",
        main_area:  "Brightstone Cove Tseldora",
        bonfire_id: 14655,
        map_id:     MapId::BrightstoneCoveTseldora,
    },
    Bonfire {
        name:       "Chapel Threshold",
        main_area:  "Brightstone Cove Tseldora",
        bonfire_id: 14660,
        map_id:     MapId::BrightstoneCoveTseldora,
    },
    Bonfire {
        name:       "Lower Brightstone Cove",
        main_area:  "Brightstone Cove Tseldora",
        bonfire_id: 14650,
        map_id:     MapId::BrightstoneCoveTseldora,
    },
    Bonfire {
        name:       "Harvel's Resting Place",
        main_area:  "Grave of Saints",
        bonfire_id: 34655,
        map_id:     MapId::GraveOfSaints,
    },
    Bonfire {
        name:       "Grave Entrance",
        main_area:  "Grave of Saints",
        bonfire_id: 34650,
        map_id:     MapId::GraveOfSaints,
    },
    Bonfire {
        name:       "Upper Gutter",
        main_area:  "The Gutter",
        bonfire_id: 25665,
        map_id:     MapId::TheGutter,
    },
    Bonfire {
        name:       "Central Gutter",
        main_area:  "The Gutter",
        bonfire_id: 25655,
        map_id:     MapId::TheGutter,
    },
    Bonfire {
        name:       "Black Gulch Mouth",
        main_area:  "Black Gulch",
        bonfire_id: 25650,
        map_id:     MapId::TheGutter,
    },
    Bonfire {
        name:       "Hidden Chamber",
        main_area:  "Black Gulch",
        bonfire_id: 25660,
        map_id:     MapId::TheGutter,
    },
    Bonfire {
        name:       "King's Gate",
        main_area:  "Drangleic Castle",
        bonfire_id: 21650,
        map_id:     MapId::DrangleicCastle,
    },
    Bonfire {
        name:       "Forgotten Chamber",
        main_area:  "Drangleic Castle",
        bonfire_id: 21660,
        map_id:     MapId::DrangleicCastle,
    },
    Bonfire {
        name:       "Under Castle Drangleic",
        main_area:  "Drangleic Castle",
        bonfire_id: 21665,
        map_id:     MapId::DrangleicCastle,
    },
    Bonfire {
        name:       "Central Castle Drangleic",
        main_area:  "Drangleic Castle",
        bonfire_id: 21655,
        map_id:     MapId::DrangleicCastle,
    },
    Bonfire {
        name:       "Tower of Prayer",
        main_area:  "Shrine of Amana",
        bonfire_id: 11650,
        map_id:     MapId::ShrineOfAmana,
    },
    Bonfire {
        name:       "Crumbled Ruins",
        main_area:  "Shrine of Amana",
        bonfire_id: 11655,
        map_id:     MapId::ShrineOfAmana,
    },
    Bonfire {
        name:       "Rhoy's Resting Place",
        main_area:  "Shrine of Amana",
        bonfire_id: 11660,
        map_id:     MapId::ShrineOfAmana,
    },
    Bonfire {
        name:       "Rise of the Dead",
        main_area:  "Shrine of Amana",
        bonfire_id: 11670,
        map_id:     MapId::ShrineOfAmana,
    },
    Bonfire {
        name:       "Undead Crypt Entrance",
        main_area:  "Undead Crypt",
        bonfire_id: 24655,
        map_id:     MapId::UndeadCrypt,
    },
    Bonfire {
        name:       "Undead Ditch",
        main_area:  "Undead Crypt",
        bonfire_id: 24650,
        map_id:     MapId::UndeadCrypt,
    },
    Bonfire {
        name:       "Foregarden",
        main_area:  "Aldia's Keep",
        bonfire_id: 15650,
        map_id:     MapId::AldiasKeep,
    },
    Bonfire {
        name:       "Ritual Site",
        main_area:  "Aldia's Keep",
        bonfire_id: 15655,
        map_id:     MapId::AldiasKeep,
    },
    Bonfire {
        name:       "Dragon Aerie",
        main_area:  "Dragon Aerie",
        bonfire_id: 27650,
        map_id:     MapId::DragonAerie,
    },
    Bonfire {
        name:       "Shrine Entrance",
        main_area:  "Dragon Shrine",
        bonfire_id: 27655,
        map_id:     MapId::DragonAerie,
    },
    Bonfire {
        name:       "Sanctum Walk",
        main_area:  "Shulva, Sanctum City",
        bonfire_id: 35650,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Tower of Prayer",
        main_area:  "Shulva, Sanctum City",
        bonfire_id: 35685,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Priestess's Chamber",
        main_area:  "Shulva, Sanctum City",
        bonfire_id: 35655,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Hidden Sanctum Chamber",
        main_area:  "Dragon's Sanctum",
        bonfire_id: 35670,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Lair of the Imperfect",
        main_area:  "Dragon's Sanctum",
        bonfire_id: 35675,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Sanctum Interior",
        main_area:  "Dragon's Sanctum",
        bonfire_id: 35680,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Sanctum Nadir",
        main_area:  "Dragon's Rest",
        bonfire_id: 35665,
        map_id:     MapId::ShulvaSanctumCity,
    },
    Bonfire {
        name:       "Throne Floor",
        main_area:  "Brume Tower",
        bonfire_id: 36650,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "Upper Floor",
        main_area:  "Brume Tower",
        bonfire_id: 36660,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "Foyer",
        main_area:  "Brume Tower",
        bonfire_id: 36655,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "Lowermost Floor",
        main_area:  "Brume Tower",
        bonfire_id: 36670,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "The Smelter Throne",
        main_area:  "Brume Tower",
        bonfire_id: 36675,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "Iron Passage",
        main_area:  "Iron Passage",
        bonfire_id: 36665,
        map_id:     MapId::BrumeTower,
    },
    Bonfire {
        name:       "Outer Wall",
        main_area:  "Frozen Eleum Loyce",
        bonfire_id: 37650,
        map_id:     MapId::FrozenEleumLoyce,
    },
    Bonfire {
        name:       "Abandoned Dwelling",
        main_area:  "Frozen Eleum Loyce",
        bonfire_id: 37660,
        map_id:     MapId::FrozenEleumLoyce,
    },
    Bonfire {
        name:       "Inner Wall",
        main_area:  "Frozen Eleum Loyce",
        bonfire_id: 37685,
        map_id:     MapId::FrozenEleumLoyce,
    },
    Bonfire {
        name:       "Lower Garrison",
        main_area:  "Frozen Eleum Loyce",
        bonfire_id: 37665,
        map_id:     MapId::FrozenEleumLoyce,
    },
    Bonfire {
        name:       "Expulsion Chamber",
        main_area:  "Frozen Eleum Loyce",
        bonfire_id: 37675,
        map_id:     MapId::FrozenEleumLoyce,
    },
    Bonfire {
        name:       "Grand Cathedral",
        main_area:  "Grand Cathedral",
        bonfire_id: 37670,
        map_id:     MapId::FrozenEleumLoyce,
    },
];
