[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wayclip-global-hotkey = { workspace = true }
linkme = { workspace = true }

gubtool-core = { version = "0.1.0", path = "../gubtool-core" }
const-str = "1.1.0"

[lints]
workspace = true
