use {
    crate::offsets::module_offsets::versions,
    gubtool_core::{attached::version, game_version::EldenRingVersion::*},
};

#[derive(Debug)]
pub struct ModuleOffsets {
    pub world_chr_man:                  u64,
    pub field_area:                     u64,
    pub game_man:                       u64,
    pub game_data_man:                  u64,
    pub menu_man:                       u64,
    pub world_area_time_impl:           u64,
    pub cs_emk_system:                  u64,
    pub virtual_mem_flag:               u64,
    pub damage_manager:                 u64,
    pub map_item_man_impl:              u64,
    pub dl_user_input_manager_impl:     u64,
    pub cs_flipper_imp:                 u64,
    pub cs_dlc_imp:                     u64,
    pub lock_tgt_man_imp:               u64,
    pub grace_warp:                     u64,
    pub block_warp:                     u64,
    pub get_player_item_quantity_by_id: u64,
    pub item_spawn:                     u64,
    pub give_runes:                     u64,
    pub get_event:                      u64,
    pub set_event:                      u64,
    pub set_speffect:                   u64,
    pub remove_speffect:                u64,
    pub get_chr_ins_by_entity_id:       u64,
    pub emevd_switch:                   u64,
    pub emk_event_ins_ctor:             u64,
    pub external_event_temp_ctor:       u64,
    pub execute_talk_command:           u64,
    pub add_cool_time:                  u64,
    pub locked_target_pointer:          u64,
    pub target_no_stagger:              u64,
    pub player_no_grab:                 u64,
    pub player_infinite_poise:          u64,
    pub warp_coord_write:               u64,
    pub warp_angle_write:               u64,
    pub get_force_act_idx:              u64,
    pub set_requested_action:           u64,
    pub no_time_pass_on_death:          u64,
    pub no_logo:                        u64,
    pub fps_cap:                        u64,
    pub mute_music:                     u64,
    pub pause_world:                    u64,
    pub torrent_disabled_underworld:    u64,
    pub whistle_disabled:               u64,
    pub open_map:                       u64,
    pub close_map:                      u64,
    pub can_fast_travel:                u64,
    pub no_rune_loss_on_death:          u64,
    pub disable_area_welcome_message:   u64,
    pub chr_dbg_flags:                  u64,
    pub map_dbg_flags:                  u64,
    pub kernel32_create_thread:         u64,
    pub kernel32_close_handle:          u64,
    pub kernel32_load_library_w:        u64,
    pub lua_event_system:               u64,
}

#[inline(always)]
pub(super) fn module_offsets() -> &'static ModuleOffsets {
    match version() {
        Some(Version1_2_0) => &versions::OFFSETS_1_2_0,
        Some(Version1_2_1) => &versions::OFFSETS_1_2_1,
        Some(Version1_2_2) => &versions::OFFSETS_1_2_2,
        Some(Version1_2_3) => &versions::OFFSETS_1_2_3,
        Some(Version1_3_0) => &versions::OFFSETS_1_3_0,
        Some(Version1_3_1) => &versions::OFFSETS_1_3_1,
        Some(Version1_3_2) => &versions::OFFSETS_1_3_2,
        Some(Version1_4_0) => &versions::OFFSETS_1_4_0,
        Some(Version1_4_1) => &versions::OFFSETS_1_4_1,
        Some(Version1_5_0) => &versions::OFFSETS_1_5_0,
        Some(Version1_6_0) => &versions::OFFSETS_1_6_0,
        Some(Version1_7_0) => &versions::OFFSETS_1_7_0,
        Some(Version1_8_0) => &versions::OFFSETS_1_8_0,
        Some(Version1_8_1) => &versions::OFFSETS_1_8_1,
        Some(Version1_9_0) => &versions::OFFSETS_1_9_0,
        Some(Version1_9_1) => &versions::OFFSETS_1_9_1,
        Some(Version2_0_0) => &versions::OFFSETS_2_0_0,
        Some(Version2_0_1) => &versions::OFFSETS_2_0_1,
        Some(Version2_2_0) => &versions::OFFSETS_2_2_0,
        Some(Version2_2_3) => &versions::OFFSETS_2_2_3,
        Some(Version2_3_0) => &versions::OFFSETS_2_3_0,
        Some(Version2_4_0) => &versions::OFFSETS_2_4_0,
        Some(Version2_5_0) => &versions::OFFSETS_2_5_0,
        Some(Version2_6_0) => &versions::OFFSETS_2_6_0,
        Some(Version2_6_1) => &versions::OFFSETS_2_6_1,
        Some(Version2_6_2) => &versions::OFFSETS_2_6_2,
        Some(Version2_7_0) => &versions::OFFSETS_2_7_0,
        _ => &versions::OFFSETS_2_6_2,
    }
}
