[package]
name = "eldenring"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
phf = { workspace = true }
thiserror = { workspace = true }
pelite = { workspace = true }
clap = { workspace = true }
once_cell = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

gubtool-core = { version = "0.1.0", path = "../gubtool-core" }
shared = { version = "0.1.0", path = "../shared" }
assemble = { version = "0.1.0", path = "../assemble" }

[build-dependencies]
assemble = { version = "0.1.0", path = "../assemble" }

[lints]
workspace = true